Repository APPSCHOOL2-Android/FinalProject-TripFriend, pull requests merged in 2023-09, with the labels that each got.

#13 Login Main Acitvity 생성
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/LoginMainActivity.kt
  TripFriend/app/src/main/res/layout/activity_login_main.xml
Labels: UI

#15 로그인 메인 화면 구현 [#2_Login_Main_UI]
  TripFriend/app/src/main/AndroidManifest.xml
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/LoginMainFragment.kt
  TripFriend/app/src/main/res/drawable/login_background_image.jpg
  TripFriend/app/src/main/res/layout/fragment_login_main.xml
Labels: UI

#20 Splash Screen 구현 (미완성)
  TripFriend/app/src/main/AndroidManifest.xml
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/LoginMainActivity.kt
  TripFriend/app/src/main/res/drawable/tripfriend.gif
  TripFriend/app/src/main/res/layout/fragment_login_main.xml
  TripFriend/app/src/main/res/values/themes.xml
Labels: UI

#31 회원가입 2단계 화면 구현
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepThreeFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepTwoFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/LoginMainActivity.kt
  TripFriend/app/src/main/res/layout/fragment_join_step_three.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_two.xml
Labels: UI

#46 회원가입 5단계 화면 및 수정 사항 반영
  TripFriend/app/src/main/AndroidManifest.xml
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/EmailLoginFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepFiveFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepFourFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepOneFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepThreeFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepTwoFragment.kt
  TripFriend/app/src/main/res/color/suggestion_chip_background_color_selector.xml
  TripFriend/app/src/main/res/color/suggestion_chip_text_color_selector.xml
  TripFriend/app/src/main/res/layout/fragment_email_login.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_five.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_four.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_one.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_three.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_two.xml
  TripFriend/app/src/main/res/mipmap-anydpi-v26/ic_trip_friend.xml
  TripFriend/app/src/main/res/mipmap-anydpi-v26/ic_trip_friend_round.xml
  TripFriend/app/src/main/res/mipmap-hdpi/ic_trip_friend.png
  TripFriend/app/src/main/res/mipmap-hdpi/ic_trip_friend_foreground.png
  TripFriend/app/src/main/res/mipmap-hdpi/ic_trip_friend_round.png
  TripFriend/app/src/main/res/mipmap-mdpi/ic_trip_friend.png
  TripFriend/app/src/main/res/mipmap-mdpi/ic_trip_friend_foreground.png
  TripFriend/app/src/main/res/mipmap-mdpi/ic_trip_friend_round.png
  TripFriend/app/src/main/res/mipmap-xhdpi/ic_trip_friend.png
  TripFriend/app/src/main/res/mipmap-xhdpi/ic_trip_friend_foreground.png
  TripFriend/app/src/main/res/mipmap-xhdpi/ic_trip_friend_round.png
  TripFriend/app/src/main/res/mipmap-xxhdpi/ic_trip_friend.png
  TripFriend/app/src/main/res/mipmap-xxhdpi/ic_trip_friend_foreground.png
  TripFriend/app/src/main/res/mipmap-xxhdpi/ic_trip_friend_round.png
  TripFriend/app/src/main/res/mipmap-xxxhdpi/ic_trip_friend.png
  TripFriend/app/src/main/res/mipmap-xxxhdpi/ic_trip_friend_foreground.png
  TripFriend/app/src/main/res/mipmap-xxxhdpi/ic_trip_friend_round.png
  TripFriend/app/src/main/res/values/strings.xml
  TripFriend/app/src/main/res/values/themes.xml
Labels: fix, UI

#47 FIX: 채팅방 프로필, DateRangePicker 수정
  TripFriend/app/build.gradle
  TripFriend/app/src/main/java/com/test/tripfriend/ui/home/HomeMainFragment.kt
  TripFriend/app/src/main/res/layout/dialog_home_main_filter.xml
  TripFriend/app/src/main/res/layout/fragment_group_chat_room.xml
  TripFriend/app/src/main/res/layout/fragment_personal_chat_room.xml
  TripFriend/app/src/main/res/layout/row_chat_room_opponent.xml
  TripFriend/app/src/main/res/layout/row_chat_room_user.xml
  TripFriend/app/src/main/res/layout/row_chatting_personal.xml
  TripFriend/app/src/main/res/layout/row_group_chat_room.xml
  TripFriend/app/src/main/res/values/strings.xml
Labels: fix

#48 UI : 동행하기 글 등록 화면 구현 (김민우)
  TripFriend/app/src/main/java/com/test/tripfriend/MainActivity.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment1.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment2.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment3.kt
  TripFriend/app/src/main/res/drawable/add_a_photo_24px.xml
  TripFriend/app/src/main/res/drawable/calendar_month_24px.xml
  TripFriend/app/src/main/res/drawable/chip_selector.xml
  TripFriend/app/src/main/res/drawable/image_border.xml
  TripFriend/app/src/main/res/layout/dialog_home_main_filter.xml
  TripFriend/app/src/main/res/layout/fragment_accompany_register1.xml
  TripFriend/app/src/main/res/layout/fragment_accompany_register2.xml
  TripFriend/app/src/main/res/layout/fragment_accompany_register3.xml
  TripFriend/app/src/main/res/layout/fragment_home_list.xml
  TripFriend/app/src/main/res/layout/fragment_home_main.xml
Labels: UI

#49 로그인 및 회원가입 화면 수정사항 반영
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/LoginMainFragment.kt
  TripFriend/app/src/main/res/drawable/kakao_talk.png
  TripFriend/app/src/main/res/drawable/kakao_talk_icon.png
  TripFriend/app/src/main/res/layout/fragment_email_login.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_five.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_four.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_one.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_three.xml
  TripFriend/app/src/main/res/layout/fragment_join_step_two.xml
  TripFriend/app/src/main/res/layout/fragment_login_main.xml
Labels: fix, UI

#52 화면 전환 대응
  TripFriend/app/src/main/AndroidManifest.xml
Labels: chore

#58 회원가입 및 로그인 화면 최종 수정 사항 반영
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/EmailLoginFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepFiveFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepFourFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepOneFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepThreeFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/JoinStepTwoFragment.kt
  TripFriend/app/src/main/res/layout/fragment_join_step_five.xml
Labels: fix, UI

#59 FIX: 채팅 UI 수정
  TripFriend/app/src/main/java/com/test/tripfriend/ui/chatting/GroupChatRoomFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/chatting/PersonalChatRoomFragment.kt
  TripFriend/app/src/main/res/drawable/border3.xml
  TripFriend/app/src/main/res/layout/fragment_group_chat_room.xml
  TripFriend/app/src/main/res/layout/fragment_personal_chat_room.xml
  TripFriend/app/src/main/res/layout/row_chat_room_opponent.xml
  TripFriend/app/src/main/res/layout/row_chat_room_user.xml
  TripFriend/app/src/main/res/layout/row_chatting_group.xml
  TripFriend/app/src/main/res/layout/row_chatting_personal.xml
Labels: fix

#67 내정보 화면 파이어스토어 연동
  TripFriend/app/build.gradle
  TripFriend/app/src/main/java/com/test/tripfriend/dataclassmodel/User.kt
  TripFriend/app/src/main/java/com/test/tripfriend/repository/UserRepository.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/myinfo/MyInfoMainFragment.kt
Labels: feat

#84 내정보 수정 기능 구현
  TripFriend/app/src/main/java/com/test/tripfriend/repository/UserRepository.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/main/MainActivity.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/myinfo/ModifyMyInfoFragment.kt
  TripFriend/app/src/main/res/drawable/edit_icon.png
  TripFriend/app/src/main/res/layout/fragment_modify_my_info.xml
Labels: feat, fix

#85 feat: 동행 등록 기능 구현
  TripFriend/app/build.gradle
  TripFriend/app/src/main/java/com/test/tripfriend/dataclassmodel/TripPost.kt
  TripFriend/app/src/main/java/com/test/tripfriend/repository/AccompanyRegisterRepository.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment1.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment2.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment3.kt
  TripFriend/app/src/main/res/layout/fragment_accompany_register3.xml
Labels: feat

#103 비회원 둘러보기 기능에서 bottom navi 메뉴를 통해 회원 서비스 접근 시 제한하는 기능
  TripFriend/app/src/main/java/com/test/tripfriend/ui/main/MainActivity.kt
Labels: feat

#107 Feature/81 accompany register
  TripFriend/app/src/main/java/com/test/tripfriend/repository/HomeListRepository.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment2.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment3.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/home/HomeListFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/viewmodel/HomeViewModel.kt
  TripFriend/app/src/main/res/layout/fragment_home_list.xml
Labels: fix

#109 내정보 수정 화면 닉네임 중복검사 처리
  TripFriend/app/src/main/java/com/test/tripfriend/ui/myinfo/ModifyMyInfoFragment.kt
Labels: feat

#117 Feature/81 accompany register
  TripFriend/app/src/main/java/com/test/tripfriend/ui/home/HomeListFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/trip/ReadPostFragment.kt
Labels: fix

#121 fix: 동행 글 저장 시 멤버리스트에 닉네임 저장, 홈 목록 수정
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment3.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/home/HomeListFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/trip/ReadPostFragment.kt
Labels: fix

#134 요청 페이지 접근 시 발생하는 버그 수정
  TripFriend/app/src/main/java/com/test/tripfriend/ui/trip/ReceivedNotificationFragment.kt
Labels: bug

#153 Feature/144 home search filter
  TripFriend/app/src/main/java/com/test/tripfriend/ui/accompany/AccompanyRegisterFragment1.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/home/HomeListFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/home/HomeMainFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/home/HomeMapFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/trip/ModifyPostFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/viewmodel/HomeViewModel.kt
Labels: feat

#163 동행 요청 수락 시 알림 기능 구현
  TripFriend/app/build.gradle
  TripFriend/app/src/main/AndroidManifest.xml
  TripFriend/app/src/main/java/com/test/tripfriend/dataclassmodel/User.kt
  TripFriend/app/src/main/java/com/test/tripfriend/repository/FCMService.kt
  TripFriend/app/src/main/java/com/test/tripfriend/repository/MyFirebaseMessagingService.kt
  TripFriend/app/src/main/java/com/test/tripfriend/repository/UserRepository.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/myinfo/MyAppSettingFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/trip/ReceivedNotificationFragment.kt
  TripFriend/app/src/main/java/com/test/tripfriend/ui/user/LoginMainActivity.kt
Labels: feat, chore

#169 notification 앱 실행 시 최초 한 번만 전송되는 문제 해결
  TripFriend/app/src/main/java/com/test/tripfriend/repository/FCMService.kt
  TripFriend/app/src/main/java/com/test/tripfriend/repository/MyFirebaseMessagingService.kt
Labels: fix
